services:
  - type: web
    name: inn-hoian
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: mkdir -p .local && npm run db:push && node dist/index.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
